DavidSM64/Diddy-Kong-Racing

score.sh
tools/python/score.py

Type `./score.sh` to get the current progress of the decomp.

Added a score script

---

tools/python/score.py

Updated scoring to be based on code size, instead of number of functions.

Updated score.sh to be based on code size.

---

tools/python/split_data_regions.py

The data being worked off of for these sections is less developed and much
more noisy than the .data section, so in its current condition, there will
be comparatively more mistakes in the output for them.

Added .rodata and .bss sections to data region splitter tool.

---

README.md
tools/python/get_symbol.py

get_symbol now supports looking up RAM address given a symbol name.

Added bidirectionality to get_symbol.

---

src/controller_pak.c
src/controller_pak.h
src/fade_transition.c
src/fade_transition.h
src/memory.h
src/menu.c
src/unknown_06B2B0.c

Just want to keep large commits like this to different pulls so it makes merging easier.

controller_pak and fade_transition function signatures to headers

---

include/structs.h
lib/src/unknown_0C9C90.c
src/audio.c
src/camera.c
src/camera.h
src/particles.h
src/unknown_003260.c
src/unknown_003260.h
src/unknown_008C40.c
src/unknown_008C40.h
src/unknown_00BC20.c
src/unknown_00BC20.h
src/unknown_0255E0.c
src/unknown_0255E0.h
src/unknown_0348C0.c
src/unknown_0348C0.h
src/unknown_043920.c
src/unknown_043920.h
src/unknown_05CEF0.c
src/unknown_05CEF0.h
src/unknown_06B2B0.c
src/unknown_077C50.h
src/unknown_09F8F0.c
src/unknown_09F8F0.h
src/waves.c
src/waves.h

Several more large-ish changes for header files

---

lib/src/libc/ll.c
lib/src/libc/llcvt.c
lib/src/mips1/al/alSynAllocFX.c
src/camera.c

and `#if 0`'d the ones I couldn't fix.

Fixed some broken NON_MATCHING functions.

---

include/structs.h
src/controller_pak.c
src/unknown_00BC20.c
src/unknown_00BC20.h
src/unknown_0348C0.c

Had these laying around for a while. Figured I should push them.

Decompiled four non-matching functions.

---

src/unknown_043920.c

I've changed the comparisons to raceType to utilize the enum. 
I've also gone ahead and changed some hexadecimal values over to decimal as they look like they would make more sense.

Add RACE_TYPE enums

---

tools/python/generate_ld.py

From comment in https://github.com/DavidSM64/Diddy-Kong-Racing/pull/189.

Refactored variable.

---

lib/src/libc/ldiv.c
lib/src/mips1/al/alSynAllocFX.c
lib/src/mips1/al/synthesizer.c
lib/src/os/osTimer.c
lib/src/os/osViMgr.c
src/asset_loading.c
src/camera.c
src/controller_pak.c
src/fade_transition.c
src/font.c
src/main.c
src/memory.c
src/menu.c
src/object_models.c
src/particles.c
src/printf.c
src/textures_sprites.c
src/thread0_epc.c
src/unknown_00BC20.c
src/unknown_0255E0.c
src/unknown_032760.c
src/unknown_0348C0.c
src/unknown_043920.c
src/unknown_06B2B0.c
src/unknown_077C50.c
src/unknown_078050.c
src/video.c

We will enable NON_MATCHING on a case by case basis going forward

Rename ALL NON_MATCHING to NON_EQUIVALENT. 

---

src/particles.c
src/particles.h

Was just perusing around this file and found a couple low hanging fruit changes to clean up some warnings.

Particles warnings fixes

---

Makefile
tools/dkr_assets_tool.cpp

Also added fix for when dkr.ld is manually deleted, suggested by David.

Clean up dkr_assets_tool.cpp.

---

src/game.c
src/unknown_0255E0.c

fix non equivalent builds

---

lib/src/al/alHeapDBAlloc.c
lib/src/al/alSynSetFXMix.c
lib/src/al/load.c
lib/src/al/resample.c
lib/src/libc/rmonPrintf.c
lib/src/libc/xprintf.c
lib/src/os/contpfs.c

I'm always on a mission to clean up as many warnings as I can while keeping the code compiling properly. This commit fixes all warnings currently found in the lib folder.

Fixed all lib file warnings

---

.github/workflows/VerifyBuild.yml
.github/workflows/VerifyPR.yml

cuts build & verify time down quite a bit

download recomp binaries instead of building

---

.github/workflows/VerifyPR.yml
README.md
score.sh

Updates score in README.md automatically on PR verify

Add automatic score updater

---

.github/workflows/VerifyPR.yml
score.sh

also small fix for the score.sh script itself

update score-updater step to push to PR branch, not default branch

---

src/menu.c
src/menu.h

Identified w/ project64 debugger/breakpoints

name D_800DF4E0->gNeedToCloseDialogueBox

---

README.md

Summarize steps to build on MacOS

Add README steps for macos build

---

README.md
src/objects.c
src/save_data.c

thanks to @Ryan-Myers & @DavidSM64 for help on `func_80072348`

Match func_8001C524

---

.github/workflows/AutoApprove.yml
.github/workflows/VerifyBuild.yml

try create PR & autoapprove action

---

src/menu.c

shoutout to @MittenzHugg & @Ryan-Myers on this one

match func_80094688

---

include/structs.h
src/unknown_0255E0.c
tools/python/score.py

``` 
=====================================================================
ADVENTURE ONE (ASM -> C Decompilation)
-------------------------- 38.96% Complete --------------------------
---------------------------- Game Status ----------------------------
Balloons: 19/47, Keys: 2/4, Trophies: 1/5
T.T. Amulets: 2/4, Wizpig Amulets: 1/4
---------------------------------------------------------------------
We are collecting silver coins in Snowball Valley. (6/8 silver coins)
=====================================================================
```

Fixed score script. Also decompiled func_80028CD0

---

src/menu.c
src/menu.h
src/unknown_078050.c
src/unknown_078050.h

Only 1 warning remains, which is a bug from the original developers.

Fixed warnings in menu.c

---

README.md
tools/python/score.py
update-score.sh

Score summary

---

README.md

Score update

---

generate_ctx.sh
tools/python/m2ctx.py

* `if(segment->numberOfBatches >);` should no longer appear.
* Fixed ParticleData appearing after Particle
* Fixed the DRAW_TABLE_* macros not being preprocessed properly.

Fixed generate_ctx.py

---

tools/python/m2ctx.py

Fixed some more issues by removing text within braces when parsing function prototypes. It will also now manually insert `osTvType` and remove the useless `OSPifRam ;` if found.

For real this time.

---

README.md
src/waves.c

This PRs score update includes the match from https://github.com/DavidSM64/Diddy-Kong-Racing/pull/516 and should therefore be merged after it.
waves.c now has 1 non equiv and 7 "non attempted" functions left 🎉

match func_800B82B4 and func_800B9C18

---

README.md
src/waves.c

waves.c now has 1 non equiv and 6 "non attempted" functions left 🎉

match: func_800BA4B8

---

README.md
src/camera.c
src/waves.c

I did not verify whether func_800BBF78 is non matching or not, however the diff in decomp.me seems quite small.

partial waves.c matches for func_800BBF78 and func_800BDC80

---

README.md
include/structs.h
src/tracks.c
src/waves.c
src/waves.h

Only 2 functions left for waves.c now 🎉

match: func_800BE654

---

README.md
include/structs.h
src/waves.c

This leaves waves.c with only 1 unmatched func

match: func_800BCC70

---

README.md
src/tracks.c
src/tracks.h

Note: func_8002E904 looks very similar to this

match: func_8002FF6C

---

README.md
include/structs.h
src/textures_sprites.c
src/tracks.c

Another F3D func ~~bytes~~ bites the dust

match: func_80027184

---

README.md
src/tracks.c

Another F3D func ~~bytes~~ bites the dust

match: func_8002581C

---

README.md
src/menu.c
src/textures_sprites.c

match: func_8008F618

---

README.md
src/printf.c
src/printf.h

match: func_800B653C

---

README.md
src/textures_sprites.c

Only **two** more F3D funcs to go

match: func_8007CDC0

---

README.md
include/structs.h
src/game_ui.c
src/textures_sprites.c
src/tracks.c
src/waves.c

Improves match for func_80028050. decomp.me: https://decomp.me/scratch/E1DFy
Match credits for func_8007CA68 goes to @DavidSM64

partial match: func_80028050

---

src/menu.c
src/object_models.c
src/objects.c
src/racer.c

Snuck in my WIP of func_80060EA8 as well as it was what I was working on when starting this

Quick fix for score script

---

README.md
src/objects.c
src/printf.c
src/racer.c
src/tracks.c

This PR only matches / changes func_80018CE0, the other changes were done by format.sh

match: func_80018CE0

---

.github/workflows/UpdateScore.yml
.github/workflows/VerifyAllVersions.yml
.github/workflows/VerifyBuild.yml
.github/workflows/VerifyNonEquivalent.yml
.github/workflows/VerifyNonMatching.yml
README.md
src/objects.c

match: func_800159C8

---

libultra/src/libc/ldiv.c
src/menu.c

GCC built roms will now boot. Fixed a recently found UB, but I'm sure there's still many more out there.

Fix GCC building
