Makefile, tools/Makefile, tools/dkr_extractor_classes/ThreadPool.h, tools/dkr_extractor_classes/config.cpp, tools/dkr_extractor_classes/config.h, tools/dkr_extractor_classes/extract.cpp, tools/dkr_extractor_classes/extract.h, tools/dkr_extractor_classes/extract_binary.cpp, tools/dkr_extractor_classes/extract_binary.h, tools/dkr_extractor_classes/extract_compressed.cpp, tools/dkr_extractor_classes/extract_compressed.h, tools/dkr_extractor_classes/extract_textures.cpp, tools/dkr_extractor_classes/extract_textures.h
dkr_extractor will now use all the threads in a user's system to extract assets, which should make it much faster. Also added the reset rule to the makefile. Doing `make reset` will not only remove the `build` folder, but also remove the `assets` & `ucode` folders as well.
=> Updated dkr_extractor to be multithreaded.

tools/python/file_util.py, tools/python/split_data_regions.py
This uses a greedy algorithm and can, in theory, overpredict the starting
address of the glabels per file. However, this should at the very least be
a good starting point for separating out the data sections into their
corresponding c files.
=> Added tool to automatically split data sections by c file.

src/unknown_0777A0.c, src/unknown_080500.c, tools/python/split_data_regions.py
The output now matches up with the manually-created splits up to
unknown_0C8450.c (start of lib files).
=> Fixed issues with data region splitter.

tools/python/calc_func_checksums.py, tools/python/file_util.py
Turns out using `list()` is a lot slower than using `bytearray()`
=> Made calc_func_checksums.py a lot faster

lib/asm/non_matchings/unknown_0CA730/__f_to_ll.s, lib/asm/non_matchings/unknown_0CA730/__ll_to_f.s
While these weren't used in the vanilla game, they are very useful for modding purposes.
=> Added __d_to_ull, __f_to_ull, __ll_to_d, __ull_to_d, and __ull_to_f

Makefile
Make NON_EQUIVALENT builds define NON_MATCHING by default, which will automatically fix build errors for NON_EQUIVALENT.
=> Define NON_MATCHING when building with NON_EQUIVALENT

README.md, tools/python/score_display.py, update-score.sh
`tools/python/score_display.py` added trailing whitespace to the score which was annoying when pasting it into the README as it made git mad
=> fix trailing spaces in generated score

.github/workflows/VerifyBuild.yml
- On VerifyBuild (runs on commits on master), will run `./update-score.sh` and commit the changes made to `README.md`
- `secrets.GITHUB_TOKEN` shouldn't need to be explicitly added, as long as `Repository Settings > Actions > General > Workflow Permissions > Read and Write permissions` is enabled for the repo.
- If there are no changes to `README.md` after running `./update-score.sh`, it just wont commit anything (but if date changes, it will)
Tested it on my fork https://github.com/tonyspumoni/Diddy-Kong-Racing (latest commit just shows it updating the date, but thats only because I force pushed and overwrote the one that did it automatically)
=> add update score to verifyBuild

include/macros.h, src/object_functions.h, src/objects.h, src/particles.c, src/unknown_003260.h, tools/python/m2ctx.py
Fixed an issue where types in structs were not being extracted if it was a single line. Also added the `INCONSISTENT` define to suppress the inconsistent function signature warning from `./generate_ctx.sh`
=> Updated generate_ctx script

Makefile, tools/python/calc_func_checksums.py, tools/python/generate_ld.py
* We were using the c preprocessor on dkr.ld and outputting it to the build folder, then proceeded to use the original anyway. Fixed the makefile so that we now use the one in the build folder.
* Apparently Ubuntu 23.04 makes the dkr.map file use 8-digit addresses/offsets instead of 16 like before. I fixed a regex so that both 8 digit and 16 digit addresses should work.
* For modded repos, you can now use `/* RAM_POS: auto */` at the top of a source file. This lets generate_ld.sh still pick up the file, even if you don't care where in RAM it should be.
=> Some minor fixes

LICENSE.md
All past contributors agreed (see: https://github.com/DavidSM64/Diddy-Kong-Racing/issues/399), so this PR simply adds the license to the repo.
=> Added CC0 License

asm/non_matchings/menu/draw_menu_elements.s, asm/non_matchings/menu/func_8007FFEC.s, asm/non_matchings/menu/func_80080580.s, asm/non_matchings/menu/func_80080BC8.s, asm/non_matchings/menu/func_80081218.s, asm/non_matchings/menu/func_80083098.s, asm/non_matchings/menu/func_80084854.s, asm/non_matchings/menu/func_800871D8.s, asm/non_matchings/menu/func_8008F618.s, asm/non_matchings/menu/func_80092188.s, asm/non_matchings/menu/func_80094D28.s, asm/non_matchings/menu/func_80096978.s, asm/non_matchings/menu/func_80098774.s, asm/non_matchings/menu/load_menu_text.s, asm/non_matchings/menu/menu_credits_loop.s, asm/non_matchings/menu/menu_ghost_data_init.s, asm/non_matchings/menu/menu_track_select_init.s, asm/non_matchings/menu/render_file_select_menu.s, asm/non_matchings/menu/render_track_select_setup_ui.s, lib/src/mips1/al/alSynStartVoiceParams.h, rename.sh, src/menu.c
Taking on the big scary file.
There are still several unlabeled symbols in the `.data` section of menu.c, but this PR gets most of those labeled. Still need to do the .bss section though.
Also added an optional third argument to `rename.sh` which can be used to check to see if the new symbol already exists in the repo.
=> Renamed a lot of symbols in menu.c

.github/workflows/VerifyBuild.yml, .github/workflows/VerifyPR.yml, Makefile, README.md
- support make 4.4 syntax for C and asm file lists
- prefer clang for C preprocessing since gcc on macOS is a clang alias
- update macOS setup and build instructions
=> Update makefile and README for macOS and depdencies

asm/entrypoint.s
Ensure that the entrypoint is marked with `.ent`.
=> Fix entrypoint

src/memory.h, tools/python/m2ctx.py
StereoPanMode now gets included again, removed instances of __stdcall, and removed a trailing comma from MempoolFlags.
The tool will still generate a bunch of warnings of other little things we need to fix, but this PR fixes the immediate issues.
=> Fixed m2ctx.py issues

Makefile, asm/entrypoint.s, asm/llmuldiv_gcc.s, lib/src/libc/llcvt.c, src/main.c, src/main.h, src/object_functions.c, tools/python/gcc_generate.py
Ported over the GCC building system from DkrMod, since it's reasonably unintrusive.
Currently it defaults to IDO regardless of if you're trying to build a nonmatching copy, simply since I can't guarantee 100% GCC doesn't mess with things. (though I'm sure it's like 99.9% fine at minimum)
=> Add GCC building support

include/structs.h, src/audio_vehicle.c, src/audio_vehicle.h, src/audiosfx.c, src/camera.c, src/camera.h, src/game_ui.c, src/menu.c, src/object_functions.c, src/objects.c, src/objects.h, src/particles.c, src/particles.h, src/racer.c, src/textures_sprites.c, src/weather.c, ver/symbols/symbol_addrs.jpn.v79.txt, ver/symbols/symbol_addrs.pal.v77.txt, ver/symbols/symbol_addrs.pal.v80.txt, ver/symbols/symbol_addrs.us.v77.txt, ver/symbols/symbol_addrs.us.v80.txt
Fixes a lot of warnings, as well.
I was working on `func_8000B750` when I noticed that Asset20 is Object_Boost, so I decided to clean that up, and somehow that lead me to convert unk80068514_arg4 to Sprite as well.
Then I fell into the trap of trying to fix all of our warnings. So I figured rather than let this get out of hand, I should submit it now.
=> Convert Asset20 to Object_Boost and convert unk80068514_arg4 to Sprite

requirements.txt, tools/python/score.py
This PR introduces the ability to pass a `--treemap` parameter to the score.py script.
It will generating a treemap .html file to show decomp progress.
It ain't pretty, but it gives us a vague picture which files have the most unmatched functions in a visual way.
=> Extend score.py script to generate treemap file for decomp progress

README.md, include/structs.h, src/menu.c, src/object_models.c, src/objects.c, src/objects.h, src/particles.c, src/printf.c, src/racer.c, src/racer.h, src/tracks.c, src/waves.c
- Added decomp.me links for all remaining functions
- Added compilable non equivalent code for all funcs that hadn't had it yet
- Marked remaining funcs as non equiv (where applicable)
- Additionally sneaked in a match for func_8000E79C
=> document: remaining funcs, add decomp.me links

README.md, src/hasm/math_util.c, src/objects.c, src/objects.h, src/printf.c, tools/python/score.py
The score script was accidentally counting functions that are matched in US 1.0, but not in JPN. This will remove them from the list of GLOBAL_ASM remaining.
It's still possible I've made a mistake here, this script is tricky for me to figure out. Not sure why our score went down yet, but it does at least match the other progress script we have finally, so I'm reasonably confident it's accurate now. Might want to get some extra eyes to confirm though.
=> Fix score script miscalculations, and add final NON_EQUIVALENT function to codebase.

include/PR/gbi.h, include/PR/gu.h, include/f3ddkr.h, src/hasm/entrypoint.s, src/hasm/math_util.s, src/lights.c, src/object_functions.c, src/objects.h, src/set_rsp_segment.c, src/set_rsp_segment.h, src/tracks.c
This PR will change the gbi.h to match one found in an older version of libultra, specifically version E. This is done because it turns out we know they based their gbi.h on that version due to a specific change done to the `TXL2WORDS_4b` macro. That macro was updated in all later versions of this file, and we require the older version without the MAX.
This also cleans up our gbi.h to remove references to F3DEX2 which we don't use anyway.
=> Update gbi.h to use one found in libultra E version
